build: off

environment:
  matrix:
    - GHCVER: 9.4.8
    - GHCVER: 9.6.7

install:
  - ps: |
      # Install MSYS2
      choco install msys2
      refreshenv
      Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
      refreshenv

      # Install Haskell
      choco install haskell-dev
      refreshenv
      $env:Path = "C:\tools\ghc-$env:GHCVER\bin;C:\ghcup\bin;$env:Path"
      C:\tools\msys64\usr\bin\bash.exe -lc "cabal update"

      # Install MSYS2 packages
      C:\tools\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
      
      # Install build tools
      C:\tools\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm \
        autoconf \
        autogen \
        automake \
        libtool \
        gcc \
        git \
        mingw-w64-x86_64-libunwind \
        mingw-w64-x86_64-toolchain \
        mingw-w64-x86_64-make \
        mingw-w64-x86_64-cmake \
        mingw-w64-x86_64-autotools \
        mingw-w64-x86_64-pkg-config"

      # Install image format dependencies
      C:\tools\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm \
        mingw-w64-x86_64-libtiff \
        mingw-w64-x86_64-libwebp \
        mingw-w64-x86_64-freetype"

      # Install harfbuzz after freetype
      C:\tools\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm mingw-w64-x86_64-harfbuzz"

      # Install Qt base and core
      C:\tools\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm \
        mingw-w64-x86_64-qt5-base \
        mingw-w64-x86_64-qt5-tools \
        mingw-w64-x86_64-qt5-translations"

      # Install Qt modules
      C:\tools\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm \
        mingw-w64-x86_64-qt5-declarative \
        mingw-w64-x86_64-qt5-graphicaleffects \
        mingw-w64-x86_64-qt5-imageformats \
        mingw-w64-x86_64-qt5-multimedia \
        mingw-w64-x86_64-qt5-quickcontrols2 \
        mingw-w64-x86_64-qt5-svg \
        mingw-w64-x86_64-qt5-winextras \
        mingw-w64-x86_64-angleproject"

test_script:
  - ps: |
      $env:Path = "C:\tools\ghc-$env:GHCVER\bin;C:\ghcup\bin;C:\tools\msys64\mingw64\bin;$env:Path"
      $env:PKG_CONFIG_PATH = "C:\tools\msys64\mingw64\lib\pkgconfig"
      C:\tools\msys64\usr\bin\bash.exe -lc "cd /c/projects/hsqml && \
        cabal configure --enable-tests --ghc-options='-Wno-error=unused-imports -Wno-error=orphans' && \
        cabal build --enable-tests --ghc-options='-Wno-error=unused-imports -Wno-error=orphans' && \
        cabal run hsqml-test1 --ghc-options='-Wno-error=unused-imports -Wno-error=orphans'"

cache:
  - C:\Users\appveyor\AppData\Roaming\cabal\store
  - dist-newstyle 
