name: CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.7'
        cabal-version: '3.10.3.0'

    - name: Cache Cabal packages
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-ghc-9.6.7-cabal-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-ghc-9.6.7-cabal-

    - name: Update Cabal package list
      run: cabal update

    - name: Install Qt dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y qtdeclarative5-dev qml-module-qtquick-controls2 libqt5quick5 qt5-image-formats-plugins qtmultimedia5-dev qml-module-qtmultimedia qttools5-dev-tools qtbase5-dev

    - name: Install Qt dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install qt@5

    - name: Install Qt dependencies (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        pacman -S --noconfirm mingw-w64-x86_64-qt5-base mingw-w64-x86_64-qt5-declarative mingw-w64-x86_64-qt5-graphicaleffects mingw-w64-x86_64-qt5-imageformats mingw-w64-x86_64-qt5-multimedia mingw-w64-x86_64-qt5-quickcontrols2 mingw-w64-x86_64-qt5-svg mingw-w64-x86_64-qt5-tools mingw-w64-x86_64-qt5-translations mingw-w64-x86_64-qt5-winextras mingw-w64-x86_64-angleproject

    - name: Setup Xvfb (Linux only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y xvfb
        echo "export DISPLAY=:99.0" >> $GITHUB_ENV
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Configure
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cabal configure --enable-tests --enable-benchmarks -v2

    - name: Build
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cabal build

    - name: Test
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cabal test

    - name: Check
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cabal check

    - name: Create source distribution
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: cabal sdist

    - name: Verify source distribution
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: |
        SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz
        cd dist
        cabal install --force-reinstalls "$SRC_TGZ"

    - name: Test GHCi
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      run: echo 'do {Graphics.QML.Debug.setDebugLogLevel 0; putStrLn "OK"}' | ghci | grep OK
